### ISSUE TITLE
Unable to execute get_demo_data

### ISSUE THREAD

**Issue by heemonsu** [go2sea/DQfD#4]
Hi! I have been trying to understand the paper's algorithm using your code, but I am  unable to execute your code properly.
The error I get is when the code gets into running get_demo_data. I get this error:

`ValueError: Dimensions must be equal, but are 4 and 24 for 'get_demo_data/eval_net/l1/MatMul' (op: 'MatMul') with input shapes: [?,4], [2,24].`

This error comes which building the layer `l1` in the DQfDDDQN.py 

I tried using `transpose_a=True` but it just led me to further errors in other parts. 
Thanks for your help and great work on the code!

**Comment by go2sea** [comment]
Fixed. Thanks！

**Comment by smasoudn** [comment]
Thanks for the nice work!
I still get the same error in line 95 of `DQfD_V3.py` where `dense1 = tf.nn.relu(tf.matmul(state, w1 + b1)`.
The error is:

    Dimensions must be equal, but are 4 and 2 for DQfD_0/eval_net/l1/MatMul (op:'Matmul') with input shapes: [?,4], [2,24].

Could you please take a look into this issue?
thanks,
